<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Description>OElite.Restme Redis provider implementation</Description>
        <TargetFrameworks>net9.0;net8.0</TargetFrameworks>
        <AssemblyVersion>2.0.5</AssemblyVersion>
        <VersionPrefix>2.0.5</VersionPrefix>
        <AssemblyName>OElite.Restme.Redis</AssemblyName>
        <PackageTags>OElite;Restme;Redis;Cache</PackageTags>
        <RepositoryUrl>https://oelite.visualstudio.com/Uranus</RepositoryUrl>
        <Authors>OElite Limited</Authors>
        <Copyright>OElite Limited</Copyright>
        <PackageProjectUrl>https://www.oelite.com</PackageProjectUrl>
        <Title>OElite.Restme.Redis</Title>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="StackExchange.Redis" Version="2.9.17" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\OElite.Restme\OElite.Restme.csproj" />
    </ItemGroup>
</Project>
