trigger:
  - develop
  - uat

pool: oelite-build-agents

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'OElite Platform Azure Subscription(10136124-f099-450c-a694-41ac5b6560a8)'
    KeyVaultName: 'oelite-devops-cred'
    SecretsFilter: '*'
    RunAsPreJob: true