<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net9.0;net8.0</TargetFrameworks>
        <AssemblyVersion>2.0.6</AssemblyVersion>
        <VersionPrefix>2.0.6</VersionPrefix>
        <AssemblyName>OElite.Restme.GoogleUtils</AssemblyName>
        <PackageTags>RESTme;HTTP;REST;RESTful-Client;AzureBlob-Client;Redis;RedisClient;AzureStorage;.Net-Core</PackageTags>
        <RepositoryUrl>https://oelite.visualstudio.com/Uranus</RepositoryUrl>
        <Nullable>enable</Nullable>
        <Authors>OElite Limited</Authors>
        <Copyright>OElite Limited</Copyright>
        <PackageProjectUrl>https://www.oelite.com</PackageProjectUrl>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\OElite.Restme\OElite.Restme.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2"/>
    </ItemGroup>

</Project>
