<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
        <VersionPrefix>2.1.0</VersionPrefix>
        <AssemblyVersion>2.1.0</AssemblyVersion>
        <Authors>OElite Limited</Authors>
        <Owners>OElite Limited</Owners>
        <Title>OElite.Restme.MongoDb</Title>
        <Copyright>OElite Limited</Copyright>
        <PackageProjectUrl>https://www.oelite.com</PackageProjectUrl>
        <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
        <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
        <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
        <DebugType Condition="'$(OS)' != 'Windows_NT'">portable</DebugType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="MongoDB.Driver" Version="2.28.0"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\OElite.Restme.Utils\OElite.Restme.Utils.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

</Project>
