<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Description>OElite.Restme S3 provider implementation</Description>
        <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
        <AssemblyVersion>2.1.1</AssemblyVersion>
        <VersionPrefix>2.1.1</VersionPrefix>
        <AssemblyName>OElite.Restme.S3</AssemblyName>
        <PackageTags>OElite;Restme;S3;AWS;Storage</PackageTags>
        <RepositoryUrl>https://oelite.visualstudio.com/Uranus</RepositoryUrl>
        <Authors>Phanes Technology Ltd</Authors>
        <Copyright>Phanes Technology Ltd</Copyright>
        <PackageProjectUrl>https://www.oelite.com</PackageProjectUrl>
        <Title>OElite.Restme.S3</Title>
        <Nullable>enable</Nullable>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="AWSSDK.S3" Version="3.7.401" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\OElite.Restme\OElite.Restme.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>
</Project>
